### ISSUE TITLE
Is libevhtp thread-safe?

### ISSUE THREAD

**Issue by grkhetan** [ellzey/libevhtp#32]
Basically if I listen for and parse http connections in one thread -- and send it over to some other thread for processing -- which then tries to reply to the original connection, will it work?   It does not work with libevent's default evhttp support.... that one requires me to respond to the connection from the same thread which received the connection via lib event.

**Comment by adamel** [comment]
This is an issue tracker, not a forum.
https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

**Comment by ArtemGr** [comment]
> Asking questions on issue tracker may be DoS attack to developers. Use user forum for discussion, if it exists.

I haven't seen any forum links in the readme.
I'm using `libevhtp` in one of my projects and would like to have the answer as well.
Is is docummented somewhere?
If not, then it's a documentation issue.

**Comment by tjk** [comment]
See https://github.com/ellzey/libevhtp/blob/develop/examples/thread_design.c for an example on having multiple threads handle different requests. As far as inter-request-thread communication that is a trickier task (and possibly the wrong approach for your problem), but would be doable (with your own synchronization strategy).

**Comment by ArtemGr** [comment]
@tjk That's something, thanks. I remember browsing thread_design.c. But thread compatibility of libevhtp is still a mystery to me.

(See https://www.ibm.com/developerworks/library/j-jtp09263/ if you don't know what I mean).

In particular, can libevhtp structures be used from different threads, provided that they are never used at the same time. In other words, can they be sent across threads?

Some libraries are thread-compatible because their structures are in no way linked to the threads. You can move the structures between the threads, or access them from the different threads with the presence of synchronization and you will be okay.

Other libraries use thread-locals or what not for internal optimizations. Using them from a different thread might give surprising results and/or crashes.

If you can share the light on libevhtp thread compatibility, I'm sure it will be useful to future library users.

**Comment by ArtemGr** [comment]
See also "MT-Safe" and "MT-Unsafe" here: http://man7.org/linux/man-pages/man7/attributes.7.html

**Comment by tjk** [comment]
> In particular, can libevhtp structures be used from different threads, provided that they are never used at the same time. Can they be sent across threads?

I'm no expert, but I would say no. `evthr` makes it so each thread has its own` evbase` and there is some locking around callbacks (see https://github.com/ellzey/libevhtp/blob/develop/evhtp.h#L638). If you gave a better example of what you are trying to do, it would be easier to answer -- but willy nilly trying to touch internals from different threads without synchronizing yourself is definitely going to run you into problems as far as I can tell.
